# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FindFriends' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FindFriends
	pod 'Alamofire'
	pod 'SwiftyJSON'
	pod 'CryptoSwift'

  target 'FindFriendsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FindFriendsUITests' do
    # Pods for testing
  end

end
